apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_USERNAME: bXktdXNlcm5hbWU= # base64 encoded value of 'my-username'
  DB_PASSWORD: bXktcGFzc3dvcmQ= # base64 encoded value of 'my-password'
